## mindspore.ops.conv1d(input, weight, bias=None, stride=1, pad_mode='valid', padding=0, dilation=1, groups=1) -〉 Tensor
对输入Tensor计算一维卷积。

- 输入：
    * input：mindspore的tensor，输入。
    * weight：mindspore的tensor，卷积核。
    * bias：mindspore的tensor，偏置。
    * stride：mindspore的tensor，步长。
    * pad_mode：str，枚举值为"same"、"valid"或"pad"，填充模式。
    * padding：int、tuple[int]、list[int]，填充的数量。
    * dilation：int、tuple[int]，卷积核元素之间的间距。
    * groups：int, 将input拆分为几组。

- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       |
| :----:      | :----:      |
| input       | input       |
| weight      | weight      |
| bias        | bias        |
| stride      | stride      |
| pad_mode    | -           |
| padding     | padding     |
| dilation    | dilation    |
| groups      | groups      |
* torch没有pad_mode参数。
* padding参数的取值和定义也不同。torch的padding参数融合了ms的pad_mode和padding两个参数的功能。


2、返回值比较

In [36]:
input = [[[-1.1790583,  -1.1461331,  -1.1132078 ],
           [-1.0473574,  -1.0144321,  -0.98150694],
           [-0.9156563,  -0.8827312,  -0.84980613]]]
weight = [[[ 0.07491168,  0.32591826],
           [-0.30162174, -0.06628297],
           [-0.30162174, -0.06628297]]]
bias = [-0.12345]

y1 = ms.ops.conv1d(ms.tensor(input), ms.tensor(weight), ms.tensor(bias))
y2 = torch.nn.functional.conv1d(torch.tensor(input), torch.tensor(weight), torch.tensor(bias))
print ('mindspore output:',y1)
print ('torch     output:',y2)

mindspore output: [[[0.13251632 0.12148706]]]
torch     output: tensor([[[0.1325, 0.1215]]])


ms不返回类型

In [44]:
input = [[[-1.1790583,  -1.1461331,  -1.1132078 ],
           [-1.0473574,  -1.0144321,  -0.98150694],
           [-0.9156563,  -0.8827312,  -0.84980613],
           [-0.9156563,  -0.8827312,  -0.84980613]]]
weight = [[[ 0.07491168,  0.32591826],
           [-0.30162174, -0.06628297]],
          [[ 0.07491168,  0.32591826],
           [-0.30162174, -0.06628297]]]
bias = [-0.12345, -0.45]

y1 = ms.ops.conv1d(ms.tensor(input), ms.tensor(weight), ms.tensor(bias), groups=2)
y2 = torch.nn.functional.conv1d(torch.tensor(input), torch.tensor(weight), torch.tensor(bias), groups=2)
print ('mindspore output:\n',y1)
print ('torch     output:\n',y2)

mindspore output:
 [[[-0.20217557 -0.20109153]
  [-0.47159967 -0.4705156 ]]]
torch     output:
 tensor([[[-0.2022, -0.2011],
         [-0.4716, -0.4705]]])


In [ ]:
对齐pad_mode和padding参数：

In [32]:
input = [[[-1.1790583,  -1.1461331,  -1.1132078 ],
           [-1.0473574,  -1.0144321,  -0.98150694],
           [-0.9156563,  -0.8827312,  -0.84980613]]]
weight = [[[ 0.07491168,  0.32591826],
           [-0.30162174, -0.06628297],
           [-0.30162174, -0.06628297]]]
bias = [-0.12345]

y1 = ms.ops.conv1d(ms.tensor(input), ms.tensor(weight), ms.tensor(bias), pad_mode="same", padding=0)
y2 = torch.nn.functional.conv1d(torch.tensor(input), torch.tensor(weight), torch.tensor(bias),padding="same")
print ('mindspore output:',y1)
print ('torch     output:',y2)

mindspore output: [[[0.13251632 0.12148706 0.34552154]]]
torch     output: tensor([[[0.1325, 0.1215, 0.3455]]])


In [33]:
y1 = ms.ops.conv1d(ms.tensor(input), ms.tensor(weight), ms.tensor(bias), pad_mode="pad", padding=4)
y2 = torch.nn.functional.conv1d(torch.tensor(input), torch.tensor(weight), torch.tensor(bias),padding=4)
print ('mindspore output:\n',y1)
print ('torch     output:\n',y2)

mindspore output:
 [[[-0.12345    -0.12345    -0.12345    -0.37761223  0.13251632
    0.12148706  0.34552154 -0.12345    -0.12345    -0.12345   ]]]
torch     output:
 tensor([[[-0.1235, -0.1235, -0.1235, -0.3776,  0.1325,  0.1215,  0.3455,
          -0.1235, -0.1235, -0.1235]]])


3、当输入类型不正确时，报错比较

In [10]:
y1 = ms.ops.conv1d(input, weight, bias)

AttributeError: 'list' object has no attribute 'ndim'

In [34]:
y2 = torch.nn.functional.conv1d(input, weight, bias)

TypeError: conv1d() received an invalid combination of arguments - got (list, list, list), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)


报错信息torch简洁明确。建议ms优化。