## mindspore.ops.diagonal(input, offset=0, dim1=0, dim2=1) -〉 Tensor
- 输入：
    * input必须为至少二维的mindspore的tensor。
    * offset/dim1/dim2都必须为int类型。
- 返回：mindspore的tensor, 数据类型与input一样。

当输入为二维数组时：

In [1]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

y1 = ms.ops.diagonal(ms.tensor(input),1,)
y2 = torch.diagonal(torch.tensor(input),1)
y3 = jnp.diagonal(input,1)
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)
print ('jax       output ->\n',y3)

mindspore output ->
 [2 6]
torch     output ->
 tensor([2, 6])
jax       output ->
 [2 6]


ms和jax不会输出类型。

当输入为三维数组时：

In [6]:
input = np.array([[[-1.2631,  0.3755, -1.5977, -1.8172],
                                    [-1.1065,  1.0401, -0.2235, -0.7938]],

                                   [[-1.7325, -0.3081,  0.6166,  0.2335],
                                    [ 1.0500,  0.7336, -0.3836, -1.1015]]])

y1 = ms.ops.diagonal(ms.tensor(input), -1, 1, 2)
y2 = torch.diagonal(torch.tensor(input), -1, 1, 2)
y3 = jnp.diagonal(input, -1, 1, 2)
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)
print ('jax       output ->\n',y3)

mindspore output ->
 [[-1.1065]
 [ 1.05  ]]
torch     output ->
 tensor([[-1.1065],
        [ 1.0500]], dtype=torch.float64)
jax       output ->
 [[-1.1065]
 [ 1.05  ]]


ms和jax不会返回类型。

In [7]:
y1 = ms.ops.diagonal(input)

TypeError: Failed calling Diagonal with "Diagonal(offset=int, dim1=int, dim2=int)(input=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Diagonal(offset=<int>, dim1=<int>, dim2=<int>)(input=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [8]:
y2 = torch.diagonal(input)

TypeError: diagonal(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [9]:
y3 = jnp.diagonal(torch.tensor(input))

TypeError: Cannot interpret 'torch.float64' as a data type

当输入类型不正确时，报错信息torch最简洁明确。建议ms优化。