## mindspore.ops.div(input, other, *, rounding_mode=None) -〉 Tensor
- 输入：
    * input/other必须为mindspore的tensor，数据类型为int或bool。
    * rounding_mode为字符串类型，可选值有：None 、 "floor" 和 "trunc"。
- 返回：mindspore的tensor。

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.lax as jlx

input = np.array([ 0.3810,  1.2774, -0.2972, -0.3719,  0.4637])
other = np.array(0.5)

y1 = ms.ops.div(ms.tensor(input), ms.tensor(other))
y2 = torch.div(torch.tensor(input), torch.tensor(other))
y3 = jlx.div(input, other)
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)
print ('jax       output ->\n',y3)

mindspore output ->
 [ 0.762   2.5548 -0.5944 -0.7438  0.9274]
torch     output ->
 tensor([ 0.7620,  2.5548, -0.5944, -0.7438,  0.9274], dtype=torch.float64)
jax       output ->
 [ 0.762   2.5548 -0.5944 -0.7438  0.9274]


ms和jax不会输出类型。

In [6]:
input = np.array([[-0.3711, -1.9353, -0.4605, -0.2917],
                  [ 0.1815, -1.0111,  0.9805, -1.5923],
                  [ 0.1062,  1.4581,  0.7759, -1.2344],
                  [-0.1830, -0.0313,  1.1908, -1.4757]])
other = np.array([ 0.8032,  0.2930, -0.8113, -0.2308])

y1 = ms.ops.div(ms.tensor(input), ms.tensor(other), rounding_mode='trunc')
y2 = torch.div(torch.tensor(input), torch.tensor(other), rounding_mode='trunc')
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)

mindspore output ->
 [[-0. -6.  0.  1.]
 [ 0. -3. -1.  6.]
 [ 0.  4. -0.  5.]
 [-0. -0. -1.  6.]]
torch     output ->
 tensor([[-0., -6.,  0.,  1.],
        [ 0., -3., -1.,  6.],
        [ 0.,  4., -0.,  5.],
        [-0., -0., -1.,  6.]], dtype=torch.float64)


In [5]:
y3 = jlx.div(input, other)

TypeError: div: arrays must have same number of dimensions, got (4, 4), (4,).

1、当输入为多维数组时, jax不接受input和other shape不一致。  
2、jax不支持向上向下取整。

In [8]:
out2 = torch.tensor([])

torch.div(torch.tensor(input), torch.tensor(other), rounding_mode='trunc', out = out2)
print ('torch     output ->\n',out2)

torch     output ->
 tensor([[-0., -6.,  0.,  1.],
        [ 0., -3., -1.,  6.],
        [ 0.,  4., -0.,  5.],
        [-0., -0., -1.,  6.]])


torch还提供了出参的方式，ms未支持。

In [10]:
y1 = ms.ops.div(input,other)

TypeError: Failed calling Div with "Div()(x=<class 'numpy.ndarray'>, y=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Div()(x=<Number, Tensor>, y=<Number, Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [11]:
y2 = torch.div(input, other)

TypeError: div(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [13]:
y3 = jlx.diag(torch.tensor(input,other))

AttributeError: module 'jax.lax' has no attribute 'diag'

当输入类型不正确时，报错信息torch最简洁明确。建议ms优化。