## mindspore.ops.matmul(input, other) -〉 Tensor/Scalar
计算两个输入的矩阵乘积。
- 输入：input和other必须为mindspore的tensor。
- 返回：mindspore的tensor或Scalar。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| other       | other       | b           |
|             | out         | precision   |
|             |             | preferred_element_type   |


* torch额外提供了out出参方式
* jax可以通过precision参数设置后端精度，preferred_element_type设置计算及返回的数据类型。

2、返回值比较

In [16]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[1, 2, 3],
                  [4, 5, 6]])
other = np.array([[[1, 2],
                  [3, 4],
                  [5, 6]]])

y1 = ms.ops.matmul(ms.tensor(input), ms.tensor(other))
y2 = torch.matmul(torch.tensor(input), torch.tensor(other))
y3 = jnp.matmul(input, other)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)
print('\n')
print ('@ output:\n',input@other)

mindspore output:
 [[[22 28]
  [49 64]]]


torch output:
 tensor([[[22, 28],
         [49, 64]]])


jax output:
 [[[22 28]
  [49 64]]]


@ output:
 [[[22 28]
  [49 64]]]


ms与jax不返回类型。

3、报错信息比较

In [17]:
y1 = ms.ops.matmul(input, other)

TypeError: Failed calling MatMulExt with "MatMulExt()(input=<class 'numpy.ndarray'>, mat2=<class 'numpy.ndarray'>)".
The valid calling should be: 
"MatMulExt()(input=<Tensor>, mat2=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [18]:
y2 = torch.matmul(input, other)

TypeError: matmul(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [19]:
input = [2, 4, 3, 1]
y3 = jnp.log10(input, other)

TypeError: log10() takes 1 positional argument but 2 were given

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。