## mindspore.ops.sum(input, dim=None, keepdim=False, *, dtype=None) -〉Tensor
按指定维度计算元素和。
- 输入：
    * input: mindspore的tensor。
    * dim: None、int、tuple(int)、list(int)以及mindspore的tensor。
    * keepdim: bool。
    * dtype: mindspore.dtype

- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| dim         | dim         | axis        |
| keepdim     | keepdim     | dtype       |
| dtype       | out         | out         |
|             |             | keepdims    |
|             |             | initial     |
|             |             | where       |
|             |             | promote_integers   |


* torch和jax都提供了out出参方式。
* ms与jax都提供了dtype用于设置返回值的数据类型。
* jax额外提供了initial、where和promote_integers参数，分别表示返回值的初始值，是否要参与计算和，以及是否要提升为整数。

2、返回值比较

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[1, 3, 4, 2],
                  [5, 2, 6, 3],
                  [8, 1, 3, 9]])

y1 = ms.ops.sum(ms.tensor(input))
y2 = torch.sum(torch.tensor(input))
y3 = jnp.sum(input)
print ('mindspore output:',y1)
print ('torch output:',y2)
print ('jax outputn',y3)

mindspore output: 47
torch output: tensor(47)
jax outputn 47


In [3]:
y1 = ms.ops.sum(ms.tensor(input), 1, keepdim=True)
y2 = torch.sum(torch.tensor(input), 1, keepdim=True)
y3 = jnp.sum(input, 1, keepdims=True)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[10]
 [16]
 [21]]


torch output:
 tensor([[10],
        [16],
        [21]])


jax output:
 [[10]
 [16]
 [21]]


* m与jax都不返回类型

使用where，来确定计算范围时：

In [4]:
where=np.array([[0, 0, 0, 0],
                [0, 1, 0, 1],
                [1, 1, 1, 0]], dtype=bool)
y3 = jnp.sum(input, 1, keepdims=True, initial=2, where=where)
print ('jax output:\n',y3)

jax output:
 [[ 2]
 [ 7]
 [14]]


3、报错信息比较

In [5]:
y1 = ms.ops.sum(input, 1)

TypeError: Failed calling SumExt with "SumExt()(input=<class 'numpy.ndarray'>, dim=int, keepdim=bool, dtype=mindspore.dtype)".
The valid calling should be: 
"SumExt()(input=<Tensor>, dim=<int, list of int, Tensor, tuple of int>, keepdim=<bool>, dtype=<mindspore.dtype>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [6]:
y2 = torch.sum(input, 1)

TypeError: sum() received an invalid combination of arguments - got (numpy.ndarray, int), but expected one of:
 * (Tensor input, *, torch.dtype dtype)
 * (Tensor input, tuple of ints dim, bool keepdim, *, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of names dim, bool keepdim, *, torch.dtype dtype, Tensor out)


In [7]:
input = [2, 4, 3, 1]
y3 = jnp.sum(input, 1)

TypeError: sum requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。