## mindspore.ops.subtract(input, other, *, alpha=1) -〉 Tensor
对两个输入进行减法操作。
- 输入：
    * input：number.Number或mindspore的tensor（数据类型为Number）。
    * other：number.Number或mindspore的tensor（数据类型为Number）。
    * alpha：number.Number。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | x           |
| other       | other       | y           |
| alpha       | alpha       | args        |
|             | out         | out         |
|             |             | where       |

* torch额外提供了out出参方式。
* jax继承自numpy.negative, 实际out和where参数不能使用。

2、返回值比较

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([0., -3., 7, -7])
other = np.array([[1, 3, 4, 2],
                  [5, 2, 6, 3],
                  [8, 1, 3, 9]])

y1 = ms.ops.subtract(ms.tensor(input), ms.tensor(other))
y2 = torch.subtract(torch.tensor(input),torch.tensor(other))
y3 = jnp.subtract(input, other)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[ -1.  -6.   3.  -9.]
 [ -5.  -5.   1. -10.]
 [ -8.  -4.   4. -16.]]


torch output:
 tensor([[ -1.,  -6.,   3.,  -9.],
        [ -5.,  -5.,   1., -10.],
        [ -8.,  -4.,   4., -16.]], dtype=torch.float64)


jax output:
 [[ -1.  -6.   3.  -9.]
 [ -5.  -5.   1. -10.]
 [ -8.  -4.   4. -16.]]


使用alpha参数：

In [3]:
y1 = ms.ops.subtract(ms.tensor(input), ms.tensor(other), alpha=2)
y2 = torch.subtract(torch.tensor(input),torch.tensor(other), alpha=2)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)

mindspore output:
 [[ -2.  -9.  -1. -11.]
 [-10.  -7.  -5. -13.]
 [-16.  -5.   1. -25.]]


torch output:
 tensor([[ -2.,  -9.,  -1., -11.],
        [-10.,  -7.,  -5., -13.],
        [-16.,  -5.,   1., -25.]], dtype=torch.float64)


* ms与jax不返回类型。

3、报错信息比较

In [4]:
y1 = ms.ops.subtract(input,other)

TypeError: Failed calling Sub with "Sub()(input=<class 'numpy.ndarray'>, other=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Sub()(input=<Number, Tensor>, other=<Number, Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [5]:
y2 = torch.subtract(input,other)

TypeError: subtract() received an invalid combination of arguments - got (numpy.ndarray, numpy.ndarray), but expected one of:
 * (Tensor input, Tensor other, *, Number alpha, Tensor out)
 * (Tensor input, Number other, Number alpha)


In [6]:
input = [2, 4, 3, 1]
y3 = jnp.subtract(input,other)

TypeError: subtract requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。