## mindspore.ops.cumsum(x, axis, dtype=None) -〉 Tensor
- 输入：
    * x必须为mindspore的tensor。
    * axis必须为int类型。
    * dtype必须为mindspore.dtype类型。
- 返回：mindspore的tensor, shape与input一样。

此接口的输入参数使用x，与其他cum系列（使用input）接口不一致，建议统一。

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[3, 4, 6, 10], [1, 6, 7, 9], [4, 3, 8, 7], [1, 3, 7, 9]])

y1 = ms.ops.cumsum(ms.tensor(input), axis = 0)
y2 = torch.cumsum(torch.tensor(input), dim = 0)
y3 = jnp.cumsum(input, axis = 0)
print ('mindspore output ->\n',y1)
print('\n')
print ('torch     output ->\n',y2)
print('\n')
print ('jax       output ->\n',y3)

mindspore output ->
 [[ 3  4  6 10]
 [ 4 10 13 19]
 [ 8 13 21 26]
 [ 9 16 28 35]]


torch     output ->
 tensor([[ 3,  4,  6, 10],
        [ 4, 10, 13, 19],
        [ 8, 13, 21, 26],
        [ 9, 16, 28, 35]])


jax       output ->
 [[ 3  4  6 10]
 [ 4 10 13 19]
 [ 8 13 21 26]
 [ 9 16 28 35]]


ms和jax不会输出类型。

In [8]:
out2 = torch.tensor([])

torch.cumsum(torch.tensor(input), dim = 0, out = out2)
print ('torch     output ->\n',out2)

torch     output ->
 tensor([[ 3.,  4.,  6., 10.],
        [ 4., 10., 13., 19.],
        [ 8., 13., 21., 26.],
        [ 9., 16., 28., 35.]])


torch还提供了出参的方式，ms未支持。

In [5]:
y1 = ms.ops.cumsum(input, axis = 0)

TypeError: Failed calling CumSum with "CumSum(exclusive=bool, reverse=bool)(input=<class 'numpy.ndarray'>, axis=int)".
The valid calling should be: 
"CumSum(exclusive=<bool>, reverse=<bool>)(input=<Tensor>, axis=<int>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [6]:
y2 = torch.cumprod(input, dim = 0)

TypeError: cumprod() received an invalid combination of arguments - got (numpy.ndarray, dim=int), but expected one of:
 * (Tensor input, int dim, *, torch.dtype dtype, Tensor out)
 * (Tensor input, name dim, *, torch.dtype dtype, Tensor out)


In [7]:
y3 = jnp.cumprod(torch.tensor(input), axis = 0)

TypeError: Cannot interpret 'torch.int64' as a data type

当输入类型不正确时，报错信息torch最简洁明确。建议ms优化。