## mindspore.ops.flatten(input, order='C', *, start_dim=1, end_dim=- 1) -〉 Tensor
- 输入：
    * input必须为mindspore的tensor。
    * order为字符串，仅支持'C'和'F'。
    * start_dim和end_dim必须为int型。
- 返回：mindspore的tensor。

In [1]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = [[[1, 2],
          [3, 4]],
          [[5, 6],
          [7, 8]]]

y1 = ms.ops.flatten(ms.tensor(input))
y2 = torch.flatten(torch.tensor(input))
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)

mindspore output ->
 [[1 2 3 4]
 [5 6 7 8]]
torch     output ->
 tensor([1, 2, 3, 4, 5, 6, 7, 8])


因为ms与torch的start_dim参数默认值不一样（ms:1，torch:0），所以结果不同。

In [5]:
y1 = ms.ops.flatten(ms.tensor(input), start_dim = 0)
y2 = torch.flatten(torch.tensor(input), start_dim = 0)
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)

mindspore output ->
 [1 2 3 4 5 6 7 8]
torch     output ->
 tensor([1, 2, 3, 4, 5, 6, 7, 8])


start_dim参数一致时，结果一致。ms不显示返回类型。

In [6]:
y1 = ms.ops.flatten(input)

TypeError: For 'flatten', argument 'input' must be Tensor.

In [7]:
y2 = torch.flatten(input)

TypeError: flatten(): argument 'input' (position 1) must be Tensor, not list

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。