## mindspore.ops.inner(input, other) -〉 Tensor
对于1D Tensor，返回两个向量的点积。对于更高的维度，返回最后一个轴上的和积。

- 输入：input和other必须mindspore的tensor。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| other       | other       | b           |
|             | out         | precision   |
|             |             | preferred_element_type        |  
* torch 除了返回值，还额外提供了使用out参数的出参的方式。
* jax 还提供了precision参数用来指定后端精度，以及preferred_element_type用来指定返回的数据类型。

2、当input和other为都为一维tensor时

In [1]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([5, 9, -2])
other = np.array([4, -1, 6])

y1 = ms.ops.inner(ms.tensor(input), ms.tensor(other))
y2 = torch.inner(torch.tensor(input), torch.tensor(other))
y3 = jnp.inner(input, other)
print ('mindspore output:',y1)
print ('torch     output:',y2)
print ('jax       output:',y3)

mindspore output: -1
torch     output: tensor(-1)
jax       output: -1


ms与jax不返回类型

3、当input和other为多维tensor时

In [2]:
input = np.array([[0.8173, 1.0874, 1.1784],
                  [0.3279, 0.1234, 2.7894]])
other = np.array([[[-0.4682, -0.7159,  0.1506],
                   [ 0.4034, -0.3657,  1.0387],
                   [ 0.9892, -0.6684,  0.1774],
                   [ 0.9482,  1.3261,  0.3917]],

                   [[ 0.4537,  0.7493,  1.1724],
                   [ 0.2291,  0.5749, -0.2267],
                   [-0.7920,  0.3607, -0.3701],
                   [ 1.3666, -0.5850, -1.7242]]])

y1 = ms.ops.inner(ms.tensor(input), ms.tensor(other))
y2 = torch.inner(torch.tensor(input), torch.tensor(other))
y3 = jnp.inner(input, other)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[[-0.98366248  1.15604072  0.29070316  2.67854428]
  [ 2.56715399  0.54524641 -0.69120226 -1.5510041 ]]

 [[ 0.1782188   2.98449726  0.73671768  1.5671635 ]
  [ 3.51152441 -0.48629243 -1.24754336 -4.43356434]]]


torch output:
 tensor([[[-0.9837,  1.1560,  0.2907,  2.6785],
         [ 2.5672,  0.5452, -0.6912, -1.5510]],

        [[ 0.1782,  2.9845,  0.7367,  1.5672],
         [ 3.5115, -0.4863, -1.2475, -4.4336]]], dtype=torch.float64)


jax output:
 [[[-0.9836624   1.1560408   0.2907032   2.6785443 ]
  [ 2.567154    0.5452463  -0.6912023  -1.551004  ]]

 [[ 0.17821883  2.9844973   0.73671764  1.5671635 ]
  [ 3.5115244  -0.48629242 -1.2475433  -4.4335647 ]]]


4、当输入类型不正确时，报错比较

In [3]:
y1 = ms.ops.inner(input, other)

TypeError: For primitive[Shape], the input argument must be Tensor, but got <class 'numpy.ndarray'>.

In [4]:
y2 = torch.inner(input,other)

TypeError: inner(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [5]:
input = [2, 4, 3, 1]
y3 = jnp.greater(input, other)

TypeError: greater requires ndarray or scalar arguments, got <class 'list'> at position 0.

报错信息torch简洁明确。建议ms优化。