## mindspore.ops.neg(input) -〉 Tensor
计算输入的相反数。
- 输入：input必须为mindspore的tensor（数据类型为Number）。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | x           |
|             | out         | args        |
|             |             | out         |
|             |             | where       |


* torch额外提供了out出参方式
* jax继承自numpy.negative, 实际out和where参数不能使用。

2、返回值比较

实数计算：

In [1]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([0., -3., 7, -7])

y1 = ms.ops.neg(ms.tensor(input))
y2 = torch.neg(torch.tensor(input))
y3 = jnp.negative(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [-0.  3. -7.  7.]


torch output:
 tensor([-0.,  3., -7.,  7.], dtype=torch.float64)


jax output:
 [-0.  3. -7.  7.]


复数计算:

In [3]:
input = np.array([1-2j, -3+4j, 5-6j])

y1 = ms.ops.neg(ms.tensor(input))
y2 = torch.neg(torch.tensor(input))
y3 = jnp.negative(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [-1.+2.j  3.-4.j -5.+6.j]


torch output:
 tensor([-1.+2.j,  3.-4.j, -5.+6.j], dtype=torch.complex128)


jax output:
 [-1.+2.j  3.-4.j -5.+6.j]


* ms与jax不返回类型。

3、报错信息比较

In [4]:
y1 = ms.ops.neg(input)

TypeError: Failed calling Neg with "Neg()(input=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Neg()(input=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [5]:
y2 = torch.neg(input)

TypeError: neg(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [6]:
input = [2, 4, 3, 1]
y3 = jnp.negative(input)

TypeError: negative requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。