## mindspore.ops.sort(input_x, axis=- 1, descending=False) -〉 Tensor Tensor
计算输入的相反数。
- 输入：
    * input_x：mindspore的tensor。
    * axis：int。
    * descending：bool。
- 返回：2个mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| axis        | dim         | axis        |
| descending  | descending  | kind (unused)|
|             | stable      | order (unused)|
|             | out         | stable      |
|             |             | descending  |


* torch额外提供了out出参方式
* jax和torch都提供了stable参数：是否保持等价元素的顺序。

2、返回值比较

一维：

In [1]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([1, 3, 5, 4, 2, 1])

y1 = ms.ops.sort(ms.tensor(input))
y2 = torch.sort(torch.tensor(input))
y3 = jnp.sort(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 (Tensor(shape=[6], dtype=Int64, value= [1, 1, 2, 3, 4, 5]), Tensor(shape=[6], dtype=Int32, value= [0, 5, 4, 1, 3, 2]))


torch output:
 torch.return_types.sort(
values=tensor([1, 1, 2, 3, 4, 5]),
indices=tensor([0, 5, 4, 1, 3, 2]))


jax output:
 [1 1 2 3 4 5]


二维:

In [2]:
input = np.array([[2, 1, 3],
                  [4, 3, 6]])

y1 = ms.ops.sort(ms.tensor(input), 1)
y2 = torch.sort(torch.tensor(input),1)
y3 = jnp.sort(input,1)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 (Tensor(shape=[2, 3], dtype=Int64, value=
[[1, 2, 3],
 [3, 4, 6]]), Tensor(shape=[2, 3], dtype=Int32, value=
[[1, 0, 2],
 [1, 0, 2]]))


torch output:
 torch.return_types.sort(
values=tensor([[1, 2, 3],
        [3, 4, 6]]),
indices=tensor([[1, 0, 2],
        [1, 0, 2]]))


jax output:
 [[1 2 3]
 [3 4 6]]


* ms返回值的value在最后，可读性差，建议关键信息提前。
* jax仅返回排序后的array，不返回indice
* ms与jax不返回类型。

3、报错信息比较

In [3]:
y1 = ms.ops.sort(input)

TypeError: For Primitive[Sort], the type of input argument[inputx] must be Tensor but got External.

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/core/utils/check_convert_utils.cc:880 CheckTensorTypeValid


In [4]:
y2 = torch.sort(input)

TypeError: sort(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [5]:
input = [2, 4, 3, 1]
y3 = jnp.sort(input)

TypeError: sort requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。