## mindspore.ops.erf(input) -〉 Tensor
- 输入：必须为Number或mindspore的tensor，数据类型为Number。
- 返回：mindspore的tensor，当输入为 int64、bool 时，返回值类型为float32，其余情况数据类型与输入一致。

In [7]:
import numpy as np
import mindspore as ms
import torch
import jax.lax as jlx

input = np.array([-1, 0, 1, 2, 3]).astype(np.float32)

y1 = ms.ops.erf(ms.tensor(input))
y2 = torch.erf(torch.tensor(input))
y3 = jlx.erf(input)
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)
print ('jax       output ->\n',y3)

mindspore output ->
 [-0.8427008  0.         0.8427008  0.9953223  0.9999779]
torch     output ->
 tensor([-0.8427,  0.0000,  0.8427,  0.9953,  1.0000])
jax       output ->
 [-0.84270084  0.          0.84270084  0.9953222   0.99997795]


ms与jax不返回类型

In [8]:
y1 = ms.ops.erf(input)

TypeError: Failed calling Erf with "Erf()(input=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Erf()(input=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [9]:
y2 = torch.erf(input)

TypeError: erf(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [13]:
input = np.array([-1, 0, 1, 2, 3])

y3 = jlx.erf(input)

TypeError: erf does not accept dtype int32. Accepted dtypes are subtypes of floating.

当输入类型不正确时，报错信息torch最简洁明确。建议ms优化。