## mindspore.ops.argsort(input, axis=- 1, descending=False) -〉 Tensor¶
- 输入：
    * input必须是mindspore的tensor类型。
    * axis必须是int。
    * descending必须是bool。
- 返回：tensor类型，值的数据类型int32。

In [6]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp
input = np.array([[2, 1, 3],
                  [6, 4, 3]])

y1 = ms.ops.argsort(ms.tensor(input), 1)
y2 = torch.argsort(torch.tensor(input), 1)
y3 = jnp.argsort(input, 1)
print ('mindspore output: \n',y1)
print ('\n')
print ('torch     output: \n',y2)
print ('\n')
print ('jax       output: \n',y3)

mindspore output: 
 [[1 0 2]
 [2 1 0]]


torch     output: 
 tensor([[1, 0, 2],
        [2, 1, 0]])


jax       output: 
 [[1 0 2]
 [2 1 0]]


ms与jax没有显示类型。

In [7]:
y1 = ms.ops.argsort(input, 1)

TypeError: For Primitive[Sort], the type of input argument[inputx] must be Tensor but got External.

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/core/utils/check_convert_utils.cc:880 CheckTensorTypeValid


In [8]:
y2 = torch.argsort(input, 1)

TypeError: argsort() received an invalid combination of arguments - got (numpy.ndarray, int), but expected one of:
 * (Tensor input, *, bool stable, int dim, bool descending)
 * (Tensor input, int dim, bool descending)
 * (Tensor input, name dim, bool descending)


当input为np.array时，ms与torch不支持。  
报错信息ms较长，建议优化仅保留ValueError的有效信息。