## mindspore.ops.logsumexp(input, axis, keep_dims=False) -〉 Tensor
按指定维度对输入求对数指数和。

- 输入:
    * input必须为mindspore的tensor，数据类型为float16或float32。
    * axis必须为int、tuple(int)或list(int)类型。
    * keep_dims必须为bool型。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | 
| :----:      | :----:      | 
| input       | input       | 
| axis        | dim         |
| keep_dims   | keepdim     |
|             | out         |
* torch提供了out出参方式。

2、返回值比较

In [2]:
import mindspore as ms
import torch

input = [[[-1.1790583,  -1.1461331,  -1.1132078 ],
          [-1.0473574,  -1.0144321,  -0.98150694]],

         [[-0.9156563,  -0.8827312,  -0.84980613],
          [-0.9156563,  -0.8827312,  -0.84980613]]]

y1 = ms.ops.logsumexp(ms.tensor(input), 1)
y2 = torch.logsumexp(torch.tensor(input), 1)
print ('mindspore output:\n',y1)
print('\n')
print ('torch     output:\n',y2)

mindspore output:
 [[-0.41789412 -0.38496876 -0.35204363]
 [-0.22250915 -0.18958402 -0.15665895]]


torch     output:
 tensor([[-0.4179, -0.3850, -0.3520],
        [-0.2225, -0.1896, -0.1567]])


ms不返回类型

3、报错信息比较

In [3]:
y1 = ms.ops.logsumexp(input, 1)

TypeError: Failed calling ReduceMax with "ReduceMax(keep_dims=bool)(x=List<List<List<float, float, float>, List<float, float, float>>, List<List<float, float, float>, List<float, float, float>>>, axis=int)".
The valid calling should be: 
"ReduceMax(keep_dims=<bool>)(x=<Tensor>, axis=<int, list of int, Tensor, tuple of int>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [4]:
y2 = torch.logsumexp(input, 1)

TypeError: logsumexp() received an invalid combination of arguments - got (list, int), but expected one of:
 * (Tensor input, tuple of ints dim, bool keepdim, *, Tensor out)
 * (Tensor input, tuple of names dim, bool keepdim, *, Tensor out)


当输入类型不正确时，报错信息torch简洁明确。建议ms优化。