## mindspore.ops.expm1(input) -〉 Tensor
- 输入：必须为mindspore的tensor
- 返回：mindspore的tensor，与输入有相同的shape。

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([2., -4., 3., -1.])

y1 = ms.ops.expm1(ms.tensor(input))
y2 = torch.expm1(torch.tensor(input))
y3 = jnp.expm1(input)
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)
print ('jax       output ->\n',y3)

mindspore output ->
 [ 6.3890561  -0.98168436 19.08553692 -0.63212056]
torch     output ->
 tensor([ 6.3891, -0.9817, 19.0855, -0.6321], dtype=torch.float64)
jax       output ->
 [ 6.389056   -0.9816844  19.085537   -0.63212055]


ms与jax不返回类型。

In [ ]:
计算expm1(x)与exp(x)-1的误差:

In [6]:
input = np.array([1e-4, 1e-6, 2e-10])

y1 = ms.ops.expm1(ms.tensor(input))-(ms.ops.exp(ms.tensor(input))-1)
y2 = torch.expm1(torch.tensor(input))-(torch.exp(torch.tensor(input))-1)
y3 = jnp.expm1(input)-(jnp.exp(input)-1)
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)
print ('jax       output ->\n',y3)

mindspore output ->
 [0. 0. 0.]
torch     output ->
 tensor([-4.3260e-17,  3.7983e-17, -1.6528e-17], dtype=torch.float64)
jax       output ->
 [-1.15906005e-08  4.63261358e-08  2.00000003e-10]


1、ms两种计算方式结果一致，无误差。  
2、jax的误差比torch的小。

In [11]:
y1 = ms.ops.expm1(input)

TypeError: Failed calling Expm1 with "Expm1()(input=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Expm1()(input=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [12]:
y2 = torch.expm1(input)

TypeError: expm1(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [13]:
input = [2, 4, 3, 1]
y3 = jnp.expm1(input)

TypeError: expm1 requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。