## mindspore.ops.full(size, fill_value, *, dtype=None) -〉 Tensor
创建一个指定shape的Tensor，并用指定值填充。

- 输入：
    * size为tuple[int]或list[int]。
    * fill_value为number.Number，不支持复数。
- 返回：mindspore.dtype，只支持 bool_ 和 number。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| size        | size        | shape       |
| fill_value  | fill_value  | fill_value  |
| dtype       | out         | dtype       |
|             | dtype       | device      |
|             | layout      |             |
|             | device      |             |
|             | requires_grad |           |
* torch和jax都提供了device参数，用于设置返回值提交到哪个设备上。
* torch额外提供了out出参，layout用于设置内存存储结构，以及requires_grad设置自动求导是否记录操作。

2、返回值比较:

fill_value数据类型为bool型时：

In [6]:
import mindspore as ms
import torch
import jax.numpy as jnp

y1 = ms.ops.full((2, 3), 0, dtype=ms.bool_)
y2 = torch.full((2, 3), 0, dtype=torch.bool)
y3 = jnp.full((2, 3), 0, dtype=bool)
print ('mindspore output:\n',y1)
print('\n')
print ('torch     output:\n',y2)
print('\n')
print ('jax       output:\n',y3)

mindspore output:
 [[False False False]
 [False False False]]


torch     output:
 tensor([[False, False, False],
        [False, False, False]])


jax       output:
 [[False False False]
 [False False False]]


fill_value类型为number时：

In [12]:
y1 = ms.ops.full((2, 3), 3.141592)
y2 = torch.full((2, 3), 3.141592)
y3 = jnp.full((2, 3), 3.141592)
print ('mindspore output:\n',y1)
print('\n')
print ('torch     output:\n',y2)
print('\n')
print ('jax       output:\n',y3)

mindspore output:
 [[3 3 3]
 [3 3 3]]


torch     output:
 tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])


jax       output:
 [[3.141592 3.141592 3.141592]
 [3.141592 3.141592 3.141592]]


ms当fill_value为浮点数时，返回值的数据类型为int，与其他两种框架不一致。  
ms与jax不返回类型。

fill_vaule为tensor或array时：

In [17]:
y1 = ms.ops.full((2, 3), ms.ops.arange(3))

ValueError: For primitive[FillV2], the size of the input [fill_value] must be equal to 1, but got 3.

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/core/utils/check_convert_utils.cc:625 CheckInteger


In [18]:
y2 = torch.full((2, 3), torch.arange(3))

TypeError: full(): argument 'fill_value' (position 2) must be Number, not Tensor

In [19]:
y3 = jnp.full((2, 3), jnp.arange(3))
print ('jax       output:\n',y3)

jax       output:
 [[0 1 2]
 [0 1 2]]


ms与torch都不支持fill_vaule为tensor，仅jax支持填充array。

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。