## mindspore.ops.floor(input) -〉 Tensor
- 输入：必须为mindspore的tensor, 根据硬件不同支持的数据类型不同：
    * Ascend: float16、float32、float64、bfloat16、int8、int16、int32、int64、uint8、uint16、uint32、uint64。
    * GPU/CPU: float16、float32、float64。
- 返回：mindspore的tensor，与输入有相同的shape。

In [5]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[ 1.44, -1.77, -3.07],
                  [ 3.86,  2.25, -3.08],
                  [-1.55, -2.48,  1.32]])

y1 = ms.ops.floor(ms.tensor(input))
y2 = torch.floor(torch.tensor(input))
y3 = jnp.floor(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch     output:\n',y2)
print('\n')
print ('jax       output:\n',y3)

mindspore output:
 [[ 1. -2. -4.]
 [ 3.  2. -4.]
 [-2. -3.  1.]]


torch     output:
 tensor([[ 1., -2., -4.],
        [ 3.,  2., -4.],
        [-2., -3.,  1.]], dtype=torch.float64)


jax       output:
 [[ 1. -2. -4.]
 [ 3.  2. -4.]
 [-2. -3.  1.]]


ms与jax不返回类型

In [6]:
y1 = ms.ops.floor(input)

TypeError: Failed calling Floor with "Floor()(input=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Floor()(input=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [7]:
y2 = torch.floor(input)

TypeError: floor(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [9]:
input = [2, 4, 3, 1]
y3 = jnp.floor(input)

TypeError: floor requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。