## mindspore.ops.nan_to_num(input, nan=None, posinf=None, neginf=None) -〉 Tensor
返回值为1的Tensor，shape与输入相同。
- 输入：
    * input: mindspore的tensor。
    * nan: number。
    * posinf: number。
    * neginf: number。
- 返回：mindspore的tensor，数据类型与shape与torch相同。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | x           |
| nan         | nan         | copy(unused) |
| posinf      | posinf      | nan         |
| neginf      | neginf      | posinf      |
|             | out         | neginf      |


* torch额外提供了out出参方式

2、返回值比较

In [13]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([0, np.nan, 1, np.inf, 2, -np.inf])

y1 = ms.ops.nan_to_num(ms.tensor(input))
print ('mindspore output:\n',y1)

mindspore output:
 

TypeError: For NanToNum, the dtype of 'input' must not be float64.

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ops/infer/ops_func_impl/nan_to_num.cc:40 InferType


In [17]:
y2 = torch.nan_to_num(torch.tensor(input))
y3 = jnp.nan_to_num(input)
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

torch output:
 tensor([  0.0000e+00,   0.0000e+00,   1.0000e+00,  1.7977e+308,   2.0000e+00,
        -1.7977e+308], dtype=torch.float64)


jax output:
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00  3.4028235e+38
  2.0000000e+00 -3.4028235e+38]


In [26]:
input = np.array([0, np.nan, 1, np.inf, 2, -np.inf])

y1 = ms.ops.nan_to_num(ms.tensor(input, ms.float32))
y2 = torch.nan_to_num(torch.tensor(input))
y3 = jnp.nan_to_num(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00  3.4028235e+38
  2.0000000e+00 -3.4028235e+38]


torch output:
 tensor([  0.0000e+00,   0.0000e+00,   1.0000e+00,  1.7977e+308,   2.0000e+00,
        -1.7977e+308], dtype=torch.float64)


jax output:
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00  3.4028235e+38
  2.0000000e+00 -3.4028235e+38]


ms不接受int型作为input，仅支持mindspore.float32数据类型。报错信息有误，报错为仅支持float64数据类型。建议整改。  
torch与jax均支持int输入。

使用posinf和neginf参数：

In [29]:
y1 = ms.ops.nan_to_num(ms.tensor(input, ms.float32), nan=888, posinf=999, neginf=-999)
y2 = torch.nan_to_num(torch.tensor(input), nan=888, posinf=999, neginf=-999)
y3 = jnp.nan_to_num(input, nan=888, posinf=999, neginf=-999)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [   0.  888.    1.  999.    2. -999.]


torch output:
 tensor([   0.,  888.,    1.,  999.,    2., -999.], dtype=torch.float64)


jax output:
 [   0.  888.    1.  999.    2. -999.]


* ms与jax不返回类型。

3、报错信息比较：

In [31]:
y2 = torch.nan_to_num(1.5)

TypeError: nan_to_num(): argument 'input' (position 1) must be Tensor, not float

In [32]:
input = [2, 4, 3, 1]
y3 = jnp.nan_to_num(input)

TypeError: nan_to_num requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。