## mindspore.ops.addmm(input, mat1, mat2, *, beta=1, alpha=1) -〉 Tensor¶
- 输入：
    input、mat1、mat2必须是mindspore的tensor类型。
    beta、alpha（可选）必须是int、float类型。
- 返回：tensor类型

In [12]:
import mindspore as ms
import torch
input = [4., 7., 1.], [6., 3., 7.]
x1 = [2., 5., 3.], [4., 2., 2.]
x2 = [3., 2., 3.], [2., 1., 1.], [9., 8., 5.]

y1 = ms.ops.addmm(ms.tensor(input), ms.tensor(x1), ms.tensor(x2))
y2 = torch.addmm(torch.tensor(input), torch.tensor(x1), torch.tensor(x2))
print ('mindspore output -> \n',y1)
print ('torch     output -> \n',y2)

mindspore output -> 
 [[47. 40. 27.]
 [40. 29. 31.]]
torch     output -> 
 tensor([[47., 40., 27.],
        [40., 29., 31.]])


ms没有显示类型

In [19]:
input = [2., 3.]
x1 = [2., 5., 3., 7.], [4., 2., 2., 7.]
x2 = [4., 7., 1.], [6., 3., 7.]

y1 = ms.ops.addmm(ms.tensor(input), ms.tensor(x1), ms.tensor(x2))

当input shape不为N时，预期失败，但概率失败，如果加上print(y1)则必在print处失败。实现bug, 且报错原因不清晰。

In [16]:
y2 = torch.addmm(torch.tensor(input), torch.tensor(x1), torch.tensor(x2))
print ('torch     output -> ',y2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x4 and 2x3)

torch报错原因清晰