## mindspore.ops.exp(input) -〉 Tensor
- 输入：必须为mindspore的tensor
- 返回：mindspore的tensor，与输入有相同的shape。

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([0.0, 1.0, 3.0])

y1 = ms.ops.exp(ms.tensor(input))
y2 = torch.exp(torch.tensor(input))
y3 = jnp.exp(input)
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)
print ('jax       output ->\n',y3)

mindspore output ->
 [ 1.          2.71828183 20.08553692]
torch     output ->
 tensor([ 1.0000,  2.7183, 20.0855], dtype=torch.float64)
jax       output ->
 [ 1.         2.7182817 20.085537 ]


ms与jax不返回类型

In [12]:
input_1 = np.array([2, 4, 3, 1])
input_2 = np.array([1, 3, 2, 3])

y1 = ms.ops.exp(ms.tensor(input_1)+ms.tensor(input_2))
print ('mindspore     output ->\n',y1)

mindspore     output ->
 

TypeError: Select CPU operator[Exp] fail! Unsupported data type!
The supported data types are input[Float64], output[Float64];input[Complex64], output[Complex64];input[Complex128], output[Complex128];input[Float32], output[Float32];,
 but get input[[const vector]{Int64}], output[[const vector]{Float32}].

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ops/kernel/common/pyboost/pyboost_utils.cc:556 GetKernelAttr


In [13]:
y2 = torch.exp(torch.tensor(input_1)+torch.tensor(input_2))
y3 = jnp.exp(input_1+input_2)
print ('torch     output ->\n',y2)
print ('jax       output ->\n',y3)

torch     output ->
 tensor([  20.0855, 1096.6332,  148.4132,   54.5982])
jax       output ->
 [  20.085537 1096.6332    148.41316    54.598152]


当在输入时做加法操作，ms会报错，且报错行在print处，不太合理。  
torch与jax都支持。

In [14]:
y1 = ms.ops.exp(input)

TypeError: Failed calling Exp with "Exp()(input=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Exp()(input=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [15]:
y2 = torch.exp(input)

TypeError: exp(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [19]:
input = [2, 4, 3, 1]
y3 = jnp.exp(input)

TypeError: exp requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。