## mindspore.ops.softmax(input, axis=- 1, *, dtype=None) -〉 Tensor
指定轴上对输入做Softmax归一化操作。
- 输入：
    * input：mindspore的tensor。
    * axis：int。
    * dtype：mindspore.dtype。
- 返回：mindspore的tensor, 数据类型和shape与 input 相同。

1、参数比较：
| mindspore   | torch       |
| :----:      | :----:      |
| input       | input       |
| axis        | dim         |
| dtype       | dtype       |

2、返回值比较

一维：

In [13]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([1., 3, 5, 4, 2, 1])

y1 = ms.ops.softmax(ms.tensor(input))
y2 = torch.softmax(torch.tensor(input), 0)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)

mindspore output:
 [0.01152193 0.08513618 0.62907599 0.23142412 0.03131985 0.01152193]


torch output:
 tensor([0.0115, 0.0851, 0.6291, 0.2314, 0.0313, 0.0115], dtype=torch.float64)


* CPU下实测，ms与torch都不接受int作为input。
* torch的dim参数无默认值，必须传参。
* ms不返回类型。

In [17]:
input = np.array([[2., 1, 3],
                  [4, 3, 6]])

y1 = ms.ops.softmax(ms.tensor(input), 1)
y2 = torch.softmax(torch.tensor(input), 1)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)

mindspore output:
 [[0.24472847 0.09003057 0.66524096]
 [0.1141952  0.04201007 0.84379473]]


torch output:
 tensor([[0.2447, 0.0900, 0.6652],
        [0.1142, 0.0420, 0.8438]], dtype=torch.float64)


3、报错信息比较

In [18]:
y1 = ms.ops.softmax(input)

TypeError: Failed calling Softmax with "Softmax(axis=int)(input=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Softmax(axis=<int, tuple of int>)(input=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [19]:
y2 = torch.softmax(input,0)

TypeError: softmax() received an invalid combination of arguments - got (numpy.ndarray, int), but expected one of:
 * (Tensor input, int dim, torch.dtype dtype, *, Tensor out)
 * (Tensor input, name dim, *, torch.dtype dtype)


当输入类型不正确时，报错信息torch简洁明确。建议ms优化。