## mindspore.ops.ones(shape, dtype=None) -〉 Tensor
创建一个值全为1的Tensor。
- 输入：
    * shape: tuple[int]]、list[int]、int或mindspore的tensor（数据类型为int32或int64）
    * dtype: mindspore.dtype
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| shape       | size        | shape       |
| dtype       | out         | dtype       |
|             | dtype      | device      |
|             | layout      |       |
|             | device      |          |
|             | requires_grad   |        |


* torch额外提供了out出参方式, layout用于设置内存存储结构，以及requires_grad设置自动求导是否记录操作。
* torch和jax都提供了device参数，用于设置返回值提交到哪个设备上。

2、返回值比较

In [2]:
import mindspore as ms
import torch
import jax.numpy as jnp

y1 = ms.ops.ones((2,3))
y2 = torch.ones((2,3))
y3 = jnp.ones((2,3))
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[1. 1. 1.]
 [1. 1. 1.]]


torch output:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


jax output:
 [[1. 1. 1.]
 [1. 1. 1.]]


指定数据类型：

In [6]:
y1 = ms.ops.ones(4, dtype=ms.bool_)
y2 = torch.ones(4, dtype=bool)
y3 = jnp.ones(4, dtype=bool)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [ True  True  True  True]


torch output:
 tensor([True, True, True, True])


jax output:
 [ True  True  True  True]


* ms与jax不返回类型。

3、报错信息比较：

In [7]:
y1 = ms.ops.ones(1.5)

TypeError: Failed calling Ones with "Ones()(shape=float, dtype=mindspore.dtype)".
The valid calling should be: 
"Ones()(shape=<int, list of int, Tensor, tuple of int>, dtype=<mindspore.dtype>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [8]:
y2 = torch.ones(1.5)

TypeError: ones(): argument 'size' (position 1) must be tuple of ints, but found element of type float at pos 0

In [9]:
y3 = jnp.ones(1.5)

TypeError: Shapes must be 1D sequences of concrete values of integer type, got (1.5,).

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。