## mindspore.ops.cummax(input, axis) -〉 Tensor
- 输入：
    * input必须为mindspore的tensor。
    * axis必须为int类型。
- 返回：元组类型，包含两个tensor。

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.lax as jlx

input = np.array([[3, 4, 6, 10], [1, 6, 7, 9], [4, 3, 8, 7], [1, 3, 7, 9]])

y1 = ms.ops.cummax(ms.tensor(input), axis = 0)
y2 = torch.cummax(torch.tensor(input), dim = 0)
y3 = jlx.cummax(input, axis = 0)
print ('mindspore output ->\n',y1)
print('\n')
print ('torch     output ->\n',y2)
print('\n')
print ('jax       output ->\n',y3)

mindspore output ->
 (Tensor(shape=[4, 4], dtype=Int64, value=
[[ 3,  4,  6, 10],
 [ 3,  6,  7, 10],
 [ 4,  6,  8, 10],
 [ 4,  6,  8, 10]]), Tensor(shape=[4, 4], dtype=Int64, value=
[[0, 0, 0, 0],
 [0, 1, 1, 0],
 [2, 1, 2, 0],
 [2, 1, 2, 0]]))


torch     output ->
 torch.return_types.cummax(
values=tensor([[ 3,  4,  6, 10],
        [ 3,  6,  7, 10],
        [ 4,  6,  8, 10],
        [ 4,  6,  8, 10]]),
indices=tensor([[0, 0, 0, 0],
        [0, 1, 1, 0],
        [2, 1, 2, 0],
        [2, 1, 2, 0]]))


jax       output ->
 [[ 3  4  6 10]
 [ 3  6  7 10]
 [ 4  6  8 10]
 [ 4  6  8 10]]


1、ms的输出value在最后面，建议提前。  
2、jax的输出为array, 不会输出最大值的索引。

In [14]:
out2 = (torch.tensor([0]),torch.tensor([0]))

torch.cummax(torch.tensor(input), dim = 0, out = out2)
print ('torch     output ->\n',out2)

torch     output ->
 (tensor([[ 3,  4,  6, 10],
        [ 3,  6,  7, 10],
        [ 4,  6,  8, 10],
        [ 4,  6,  8, 10]]), tensor([[0, 0, 0, 0],
        [0, 1, 1, 0],
        [2, 1, 2, 0],
        [2, 1, 2, 0]]))


/var/folders/wy/5yzfdb6x7pvfxh89zcmf_w780000gn/T/ipykernel_65183/2453569664.py:3: UserWarning: An output with one or more elements was resized since it had shape [1], which does not match the required output shape [4, 4]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_68u_j54pu8/croot/pytorch-select_1717607460029/work/aten/src/ATen/native/Resize.cpp:35.)
  torch.cummax(torch.tensor(input), dim = 0, out = out2)


torch还提供了出参的方式，ms未支持。

In [8]:
y1 = ms.ops.cummax(input, axis = 0)

TypeError: Failed calling Cummax with "Cummax(axis=int)(input=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Cummax(axis=<int>)(input=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [10]:
y2 = torch.cummax(input, dim = 0)

TypeError: cummax() received an invalid combination of arguments - got (numpy.ndarray, dim=int), but expected one of:
 * (Tensor input, int dim, *, tuple of Tensors out)
 * (Tensor input, name dim, *, tuple of Tensors out)


In [11]:
y3 = jlx.cummax(torch.tensor(input), axis = 0)

TypeError: Cannot interpret 'torch.int64' as a data type

当输入类型不正确时，报错信息torch最简洁明确。建议ms优化。