## mindspore.ops.rad2deg(x) -〉 Tensor
- 输入：x必须为mindspore的tensor, 数据类型为float16、float32或float64。
- 返回：mindspore的tensor, 数据类型与input一样。

In [1]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[3.142, -3.142], [6.283, -6.283], [1.570, -1.570]])

y1 = ms.ops.rad2deg(ms.tensor(input))
y2 = torch.rad2deg(torch.tensor(input))
y3 = jnp.rad2deg(input)
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)
print ('jax       output ->\n',y3)

mindspore output ->
 [[ 180.02333422 -180.02333422]
 [ 359.98937266 -359.98937266]
 [  89.95437133  -89.95437133]]
torch     output ->
 tensor([[ 180.0233, -180.0233],
        [ 359.9894, -359.9894],
        [  89.9544,  -89.9544]], dtype=torch.float64)
jax       output ->
 [[ 180.02335 -180.02335]
 [ 359.98938 -359.98938]
 [  89.95438  -89.95438]]


ms和jax不会输出类型。

In [2]:
out2 = torch.tensor([])

torch.rad2deg(torch.tensor(input), out = out2)
print ('torch     output ->\n',out2)

torch     output ->
 tensor([[ 180.0233, -180.0233],
        [ 359.9894, -359.9894],
        [  89.9544,  -89.9544]])


torch还提供了出参的方式，ms未支持。

In [3]:
y1 = ms.ops.rad2deg(input)

TypeError: The input x must be tensor

In [4]:
y2 = torch.rad2deg(input)

TypeError: rad2deg(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [5]:
y3 = jnp.rad2deg(torch.tensor(input))

TypeError: Cannot interpret 'torch.float64' as a data type

当输入类型不正确时，报错信息torch最简洁明确。建议ms优化。