## mindspore.ops.squeeze(input, axis=None) -〉 Tensor
返回删除指定维度中大小为1的维度后的Tensor。
- 输入：
    * input：mindspore的tensor（数据类型为Number）。
    * axis：int, tuple(int), list(int)。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| axis        | dim         | axis        |

2、返回值比较

实数计算：

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[[0]], [[1]], [[2]]])
print('input shape:', input.shape)

y1 = ms.ops.squeeze(ms.tensor(input))
y2 = torch.squeeze(torch.tensor(input))
y3 = jnp.squeeze(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

input shape: (3, 1, 1)
mindspore output:
 [0 1 2]


torch output:
 tensor([0, 1, 2])


jax output:
 [0 1 2]


In [3]:
y1 = ms.ops.squeeze(ms.tensor(input), 1)
y2 = torch.squeeze(torch.tensor(input),1)
y3 = jnp.squeeze(input,1)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[0]
 [1]
 [2]]


torch output:
 tensor([[0],
        [1],
        [2]])


jax output:
 [[0]
 [1]
 [2]]


* ms与jax不返回类型。

3、报错信息比较

In [4]:
y1 = ms.ops.squeeze(ms.tensor(input), 0)

ValueError: For primitive[Squeeze], the input_x.shape[0] must be equal to 1 , but got 3.

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/core/include/utils/check_convert_utils.h:225 CheckValue


In [8]:
y2 = torch.squeeze(torch.tensor(input),0)
print ('torch output:\n',y2)
print('outpur shape:', y2.shape)

torch output:
 tensor([[[0]],

        [[1]],

        [[2]]])
outpur shape: torch.Size([3, 1, 1])


In [6]:
y3 = jnp.squeeze(input, 0)

ValueError: cannot select an axis to squeeze out which has size not equal to one, got shape=(3, 1, 1) and dimensions=(0,)

当输入axis维度上的元素不为1时，ms与jax会报错提示。torch不会报错，也对输入没有其他操作。