## mindspore.ops.ones_like(input, *, dtype=None) -〉 Tensor
返回值为1的Tensor，shape与输入相同。
- 输入：
    * input: mindspore的tensor
    * dtype: mindspore.dtype
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| dtype       | dtype       | shape       |
|             | layout      | dtype       |
|             | device      | device      |
|             | requires_grad   |        |
|             | memory_format   |        |


* torch额外提供了layout用于设置内存存储结构，requires_grad设置自动求导是否记录操作以及memory_format内存存储方式。
* jax额外提供了shape参数用于覆盖input的shape。
* torch和jax都提供了device参数，用于设置返回值提交到哪个设备上。

2、返回值比较

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([0., -3., 7, -7])

y1 = ms.ops.ones_like(ms.tensor(input))
y2 = torch.ones_like(torch.tensor(input))
y3 = jnp.ones_like(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [1. 1. 1. 1.]


torch output:
 tensor([1., 1., 1., 1.], dtype=torch.float64)


jax output:
 [1. 1. 1. 1.]


通过shape参数覆盖input的shape:

In [4]:
y3 = jnp.ones_like(input, shape=(2,3))
print ('jax output:\n',y3)

jax output:
 [[1. 1. 1.]
 [1. 1. 1.]]


* ms与jax不返回类型。

3、报错信息比较：

In [5]:
y1 = ms.ops.ones_like(1.5)

TypeError: Failed calling OnesLike with "OnesLike()(x=float)".
The valid calling should be: 
"OnesLike()(x=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [6]:
y2 = torch.ones_like(1.5)

TypeError: ones_like(): argument 'input' (position 1) must be Tensor, not float

In [19]:
input = [2, 4, 3, 1]
y3 = jnp.ones_like(input)

TypeError: ones_like requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。