## mindspore.ops.broadcast_to(input, shape) -〉 Tensor
- 输入：
    * input必须是mindspore的tensor。
    * shape必须是tuple类型。
- 返回：mindspore的tensor，shape与输入shape相同，数据类型与input相同。

In [3]:
import mindspore as ms
import torch

input = [1, 2, 3]
shape = (3, 3)

y1 = ms.ops.broadcast_to(ms.tensor(input), shape)
y2 = torch.broadcast_to(torch.tensor(input), shape)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)

mindspore output:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]


torch output:
 tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


ms不返回类型

当shape不能被广播时：

In [9]:
shape = (3, 2)

y1 = ms.ops.broadcast_to(ms.tensor(input), shape)
print ('mindspore output:\n',y1)

mindspore output:
 

ValueError: For 'BroadcastTo', in order to broadcast, each dimension pair must be equal or input dimension is 1 or target dimension is -1. But got x_shape: (3), target shape: (3, 2).

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ops/view/broadcast_to_strides_calc.cc:64 BroadcastToCheck


In [10]:
y2 = torch.broadcast_to(torch.tensor(input), shape)

RuntimeError: The expanded size of the tensor (2) must match the existing size (3) at non-singleton dimension 1.  Target sizes: [3, 2].  Tensor sizes: [3]

1、ms的报错行在print处，不太合理。如不加print不报错。  
2、ms报错信息较多，建议优化。保留关键信息。