## mindspore.ops.sinh(input) -〉 Tensor
计算输入双曲正弦。
- 输入：mindspore的tensor。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | x           |
|             | out         |             |

* torch额外提供了out出参方式

2、返回值比较

输入为实数：

In [7]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[-1., 0, 1],
                  [3, -2, 5]])

y1 = ms.ops.sinh(ms.tensor(input))
y2 = torch.sinh(torch.tensor(input))
y3 = jnp.sinh(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[-1.17520119  0.          1.17520119]
 [10.01787493 -3.62686041 74.20321058]]


torch output:
 tensor([[-1.1752,  0.0000,  1.1752],
        [10.0179, -3.6269, 74.2032]], dtype=torch.float64)


jax output:
 [[-1.1752012  0.         1.1752012]
 [10.017875  -3.6268604 74.20321  ]]


实测cpu下，ms不支持输入为int，jax与torch均支持。

输入为复数：

In [9]:
input = np.array([2-5j, 7.5+3j, 1+8j])

y1 = ms.ops.sinh(ms.tensor(input))
y2 = torch.sinh(torch.tensor(input))
y3 = jnp.sinh(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [ 1.02880315e+00  +3.60766077j -8.94973938e+02+127.57551908j
 -1.70991813e-01  +1.52665955j]


torch output:
 tensor([ 1.0288e+00+3.6077j, -8.9497e+02+127.5755j, -1.7099e-01+1.5267j],
       dtype=torch.complex128)


jax output:
 [ 1.0288032e+00  +3.607661j  -8.9497400e+02+127.575516j
 -1.7099181e-01  +1.5266595j]


* ms与jax不返回类型。

3、报错信息比较

In [10]:
y1 = ms.ops.sinh(input)

TypeError: Failed calling Sinh with "Sinh()(input=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Sinh()(input=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [11]:
y2 = torch.sinh(input)

TypeError: sinh(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [12]:
input = [2, 4, 3, 1]
y3 = jnp.sinh(input)

TypeError: sinh requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。