## mindspore.ops.pow(input, exponent) -〉 Tensor
计算input中每个元素的exponent次幂。
- 输入：input和exponent必须为Number或mindspore的tensor（数据类型为number或bool_）。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | x1          |
| exponent    | exponent    | x2          |
|             | out         |             |

* torch额外提供了out出参方式

2、返回值比较

input与other，shape相同时：

In [1]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([2, 4, 5])
other = np.array([3, 0.5, 2])

y1 = ms.ops.pow(ms.tensor(input), ms.tensor(other))
y2 = torch.pow(torch.tensor(input), torch.tensor(other))
y3 = jnp.pow(input, other)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [ 8.  2. 25.]


torch output:
 tensor([ 8.,  2., 25.], dtype=torch.float64)


jax output:
 [ 8.  2. 25.]


input与other，shape不同且包含nan值时：

In [3]:
input = np.array([[np.nan, 1, 6],
                  [1.3, 3, 5]])
other = np.array([-2, 3, 1])

y1 = ms.ops.maximum(ms.tensor(input), ms.tensor(other))
y2 = torch.maximum(torch.tensor(input), torch.tensor(other))
y3 = jnp.maximum(input, other)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[-2.   3.   6. ]
 [ 1.3  3.   5. ]]


torch output:
 tensor([[   nan, 3.0000, 6.0000],
        [1.3000, 3.0000, 5.0000]], dtype=torch.float64)


jax output:
 [[nan 3.  6. ]
 [1.3 3.  5. ]]


* 当输入中有nan值时，ms与jax和torch行为不一致。
* ms与jax不返回类型。

3、报错信息比较

In [4]:
y1 = ms.ops.pow(input, other)

TypeError: Failed calling Pow with "Pow()(input=<class 'numpy.ndarray'>, exponent=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Pow()(input=<Number, Tensor>, exponent=<Number, Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [5]:
y2 = torch.pow(input, other)

TypeError: pow() received an invalid combination of arguments - got (numpy.ndarray, numpy.ndarray), but expected one of:
 * (Tensor input, Tensor exponent, *, Tensor out)
 * (Number self, Tensor exponent, *, Tensor out)
 * (Tensor input, Number exponent, *, Tensor out)


In [6]:
input = [2, 4, 3, 1]
y3 = jnp.pow(input, other)

TypeError: power requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。