## mindspore.ops.ceil(input) -〉 Tensor
- 输入：mindspore的tensor类型。数据类型不同硬件有差异。
    * Ascend: float16、float32、float64、bfloat16。
    * GPU/CPU: float16、float32、float64。
- 返回：tensor类型。

In [1]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp
input = np.array([[ 2.55, -1.87, -3.76],
                  [ 0.48,  3.85, -1.94],
                  [ 3.2,   4.56, -1.43]])

y1 = ms.ops.ceil(ms.tensor(input))
y2 = torch.ceil(torch.tensor(input))
y3 = jnp.ceil(input)
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)
print ('jax       output ->\n',y3)

mindspore output ->
 [[ 3. -1. -3.]
 [ 1.  4. -1.]
 [ 4.  5. -1.]]
torch     output ->
 tensor([[ 3., -1., -3.],
        [ 1.,  4., -1.],
        [ 4.,  5., -1.]], dtype=torch.float64)
jax       output ->
 [[ 3. -1. -3.]
 [ 1.  4. -1.]
 [ 4.  5. -1.]]


In [18]:
input = np.array([True, True, False])
y1 = ms.ops.ceil(ms.tensor(input))
print ('mindspore output ->\n',y1)

mindspore output ->
 

TypeError: For primitive[Ceil], the input argument[input_x] must be a type of {BFloat16, Float16, Float32, Float64}, but got Bool.

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/core/utils/check_convert_utils.cc:1062 CheckSubClass


In [8]:
y2 = torch.ceil(torch.tensor(input))

RuntimeError: "ceil_vml_cpu" not implemented for 'Bool'

In [2]:
y3 = jnp.ceil(input)
print ('jax output ->\n',y3)

jax output ->
 [[ 3. -1. -3.]
 [ 1.  4. -1.]
 [ 4.  5. -1.]]


当输入的数据类型为bool型时：  
1、三种框架均未标注支持bool型，实际上jax支持，ms与torch不支持。  
2、ms如果不加print(y1)则不报错，加上print后报错行在print，有点奇怪。  