## mindspore.ops.conv3d(input, weight, bias=None, stride=1, pad_mode='valid', padding=0, dilation=1, groups=1) -〉 Tensor
对输入Tensor计算二维卷积。

- 输入：
    * input：mindspore的tensor，输入。
    * weight：mindspore的tensor，卷积核。
    * bias：mindspore的tensor，偏置。
    * stride：mindspore的tensor，步长。
    * pad_mode：str，枚举值为"same"、"valid"或"pad"，填充模式。
    * padding：int、tuple[int]、list[int]，填充的数量。
    * dilation：int、tuple[int]，卷积核元素之间的间距。
    * groups：int, 将input拆分为几组。

- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       |
| :----:      | :----:      |
| input       | input       |
| weight      | weight      |
| bias        | bias        |
| stride      | stride      |
| pad_mode    | -           |
| padding     | padding     |
| dilation    | dilation    |
| groups      | groups      |
* torch没有pad_mode参数。
* padding参数的取值和定义也不同。torch的padding参数融合了ms的pad_mode和padding两个参数的功能。


2、返回值比较

In [2]:
import mindspore as ms
import torch

input = [[[[[-1.1790583,  -1.1461331,  -1.1132078 ],
           [-1.0473574,  -1.0144321,  -0.98150694],
           [-0.9156563,  -0.8827312,  -0.84980613],
           [-1.0473574,  -1.0144321,  -0.98150694]]]]]
weight = [[[[[ 0.07491168,  0.32591826],
            [-0.30162174, -0.06628297]]]]]
bias = [-0.12345]

y1 = ms.ops.conv3d(ms.tensor(input), ms.tensor(weight), ms.tensor(bias))
y2 = torch.nn.functional.conv3d(torch.tensor(input), torch.tensor(weight), torch.tensor(bias))
print ('mindspore output:\n',y1)
print ('torch     output:\n',y2)

mindspore output:
 [[[[[-0.20217557 -0.20109153]
    [-0.19783932 -0.19675523]
    [-0.09659623 -0.09551224]]]]]
torch     output:
 tensor([[[[[-0.2022, -0.2011],
           [-0.1978, -0.1968],
           [-0.0966, -0.0955]]]]])


ms不返回类型

对齐pad_mode和padding参数：

In [3]:
y1 = ms.ops.conv3d(ms.tensor(input), ms.tensor(weight), ms.tensor(bias), pad_mode="same", padding=0)
y2 = torch.nn.functional.conv3d(torch.tensor(input), torch.tensor(weight), torch.tensor(bias),padding="same")
print ('mindspore output:\n',y1)
print ('torch     output:\n',y2)

mindspore output:
 [[[[[-0.20217557 -0.20109153  0.08920156]
    [-0.19783932 -0.19675523  0.05934366]
    [-0.09659623 -0.09551224  0.10893343]
    [-0.5325312  -0.51933384 -0.19697633]]]]]
torch     output:
 tensor([[[[[-0.2022, -0.2011,  0.0892],
           [-0.1978, -0.1968,  0.0593],
           [-0.0966, -0.0955,  0.1089],
           [-0.5325, -0.5193, -0.1970]]]]])


/var/folders/wy/5yzfdb6x7pvfxh89zcmf_w780000gn/T/ipykernel_77261/2744684280.py:2: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at /private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_68u_j54pu8/croot/pytorch-select_1717607460029/work/aten/src/ATen/native/Convolution.cpp:1032.)
  y2 = torch.nn.functional.conv3d(torch.tensor(input), torch.tensor(weight), torch.tensor(bias),padding="same")


In [4]:
y1 = ms.ops.conv3d(ms.tensor(input), ms.tensor(weight), ms.tensor(bias), pad_mode="pad", padding=2)
y2 = torch.nn.functional.conv3d(torch.tensor(input), torch.tensor(weight), torch.tensor(bias),padding=2)
print ('mindspore output:\n',y1)
print ('torch     output:\n',y2)

mindspore output:
 [[[[[-0.12345    -0.12345    -0.12345    -0.12345    -0.12345
     -0.12345   ]
    [-0.12345    -0.12345    -0.12345    -0.12345    -0.12345
     -0.12345   ]
    [-0.12345    -0.12345    -0.12345    -0.12345    -0.12345
     -0.12345   ]
    [-0.12345    -0.12345    -0.12345    -0.12345    -0.12345
     -0.12345   ]
    [-0.12345    -0.12345    -0.12345    -0.12345    -0.12345
     -0.12345   ]
    [-0.12345    -0.12345    -0.12345    -0.12345    -0.12345
     -0.12345   ]
    [-0.12345    -0.12345    -0.12345    -0.12345    -0.12345
     -0.12345   ]]

   [[-0.12345    -0.12345    -0.12345    -0.12345    -0.12345
     -0.12345   ]
    [-0.12345    -0.12345    -0.12345    -0.12345    -0.12345
     -0.12345   ]
    [-0.12345    -0.12345    -0.12345    -0.12345    -0.12345
     -0.12345   ]
    [-0.12345    -0.12345    -0.12345    -0.12345    -0.12345
     -0.12345   ]
    [-0.12345    -0.12345    -0.12345    -0.12345    -0.12345
     -0.12345   ]
    [-0.12345    -0

3、当输入类型不正确时，报错比较

In [5]:
y1 = ms.ops.conv3d(input, weight, bias)

AttributeError: 'list' object has no attribute 'shape'

In [6]:
y2 = torch.nn.functional.conv3d(input, weight, bias)

TypeError: conv3d() received an invalid combination of arguments - got (list, list, list), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)


报错信息torch简洁明确。建议ms优化。