## mindspore.ops.multiply(input, other) -〉 Tensor
计算两个Tensor逐元素相乘。
- 输入：input和other必须为Number、bool或mindspore的tensor（数据类型为number或bool_）。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | x           |
| other       | other       | y           |
|             | out         | args        |
|             |             | out         |
|             |             | where       |


* torch额外提供了out出参方式。
* jax继承自numpy.multiply, 实际out和where参数不能使用。

2、返回值比较

input与other，shape相同时：

In [1]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([2, 4, 5])
other = np.array([3, 0.5, 2])

y1 = ms.ops.multiply(ms.tensor(input), ms.tensor(other))
y2 = torch.multiply(torch.tensor(input), torch.tensor(other))
y3 = jnp.multiply(input, other)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [ 6.  2. 10.]


torch output:
 tensor([ 6.,  2., 10.], dtype=torch.float64)


jax output:
 [ 6.  2. 10.]


input与other，shape不同且包含nan值时：

In [2]:
input = np.array([[np.nan, 1, 6],
                  [1.3, 3, 5]])
other = np.array([-2, 3, 1])

y1 = ms.ops.multiply(ms.tensor(input), ms.tensor(other))
y2 = torch.multiply(torch.tensor(input), torch.tensor(other))
y3 = jnp.multiply(input, other)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[ nan  3.   6. ]
 [-2.6  9.   5. ]]


torch output:
 tensor([[    nan,  3.0000,  6.0000],
        [-2.6000,  9.0000,  5.0000]], dtype=torch.float64)


jax output:
 [[ nan  3.   6. ]
 [-2.6  9.   5. ]]


* ms与jax不返回类型。

3、报错信息比较

In [3]:
y1 = ms.ops.multiply(input, other)

TypeError: Failed calling Mul with "Mul()(input=<class 'numpy.ndarray'>, other=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Mul()(input=<Number, Tensor>, other=<Number, Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [4]:
y2 = torch.multiply(input, other)

TypeError: multiply() received an invalid combination of arguments - got (numpy.ndarray, numpy.ndarray), but expected one of:
 * (Tensor input, Tensor other, *, Tensor out)
 * (Tensor input, Number other)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !numpy.ndarray!)


In [12]:
input = [2, 4, 3, 1]
y3 = jnp.multiply(input, other)

TypeError: multiply requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。