## mindspore.ops.minimum(input, other) -〉 Tensor
计算两个输入中的最小值。
- 输入：input和other必须为Number、bool或mindspore的tensor（数据类型为Number或bool）。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | x           |
| other       | other       | y           |
|             | out         |             |

* torch额外提供了out出参方式

2、返回值比较：

input与other，shape相同时：

In [1]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([1, -5, 3, 2])
other = np.array([-2, 4, 7, -6])

y1 = ms.ops.minimum(ms.tensor(input), ms.tensor(other))
y2 = torch.minimum(torch.tensor(input), torch.tensor(other))
y3 = jnp.minimum(input, other)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [-2 -5  3 -6]


torch output:
 tensor([-2, -5,  3, -6])


jax output:
 [-2 -5  3 -6]


input与other，shape不同且包含nan值时：

In [2]:
input = np.array([[np.nan, 5, 7, 4],
                  [1, -6, 3, 8]])
other = np.array([-5, 3, 6, 9])

y1 = ms.ops.minimum(ms.tensor(input), ms.tensor(other))
y2 = torch.minimum(torch.tensor(input), torch.tensor(other))
y3 = jnp.minimum(input, other)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[-5.  3.  6.  4.]
 [-5. -6.  3.  8.]]


torch output:
 tensor([[nan,  3.,  6.,  4.],
        [-5., -6.,  3.,  8.]], dtype=torch.float64)


jax output:
 [[nan  3.  6.  4.]
 [-5. -6.  3.  8.]]


* 当输入中有nan值时，ms与jax和torch行为不一致。
* ms与jax不返回类型。

3、报错信息比较

In [3]:
y1 = ms.ops.minimum(input, other)

TypeError: Failed calling Minimum with "Minimum()(input=<class 'numpy.ndarray'>, other=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Minimum()(input=<Number, Tensor>, other=<Number, Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [4]:
y2 = torch.minimum(input, other)

TypeError: minimum(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [5]:
input = [2, 4, 3, 1]
y3 = jnp.minimum(input, other)

TypeError: minimum requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。